#
#  Copyright 2023 Fred Dushin <fred@dushin.net>
#
#  SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
#

name: "Build Examples"

on: ["push", "pull_request"]

jobs:
  build_erlang_examples:
    name: "Build Erlang Examples"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:

    - uses: erlef/setup-beam@v1
      with:
        otp-version: "24"
        elixir-version: "1.11"

    - name: Checkout repo
      uses: actions/checkout@v2

    # - name: "APT update"
    #   run: sudo apt update -y

    - name: "Build rebar3"
      run: |
        cd /tmp
        git clone https://github.com/erlang/rebar3.git
        cd rebar3
        ./bootstrap

    - name: "Build Erlang Example Programs"
      run: |
        PATH=/tmp/rebar3:$PATH ./build.sh
